/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author Diegp
 */
public class APP3Y4 extends javax.swing.JFrame {

    guia4_celular total = new guia4_celular();

    /**
     * Creates new form APP3Y4
     */
    public APP3Y4() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cpu = new javax.swing.JTextField();
        pantalla = new javax.swing.JTextField();
        ram = new javax.swing.JTextField();
        garantia = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        camprincipal = new javax.swing.JTextField();
        camsecundaria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        bateria = new javax.swing.JTextField();
        btnatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Puntaje de moviles");

        jLabel2.setText("CPU numero de nucleos: ");

        jLabel3.setText("Tamaño de pantalla: ");

        jLabel4.setText("Cantidad de RAM: ");

        jLabel5.setText("Tiempo de garantia: ");

        jLabel6.setText("Precio: ");

        jLabel7.setText("Marca: ");

        jLabel8.setText("Camaras: ");

        cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuActionPerformed(evt);
            }
        });
        cpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpuKeyTyped(evt);
            }
        });

        pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pantallaKeyReleased(evt);
            }
        });

        ram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ramKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ramKeyTyped(evt);
            }
        });

        garantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                garantiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                garantiaKeyTyped(evt);
            }
        });

        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXIE", "LENOVO", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA" }));

        jCheckBox1.setText("Principal");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jCheckBox2.setText("Secundaria");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Flash");

        camprincipal.setEnabled(false);
        camprincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                camprincipalKeyReleased(evt);
            }
        });

        camsecundaria.setEnabled(false);
        camsecundaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                camsecundariaKeyReleased(evt);
            }
        });

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("Bateria: ");

        btnatras.setText("Atras");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(camprincipal)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(camsecundaria)
                                            .addGap(185, 185, 185))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jCheckBox2)
                                                    .addGap(45, 45, 45)
                                                    .addComponent(jCheckBox3)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnatras)
                                                .addComponent(bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(104, 104, 104))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jButton1))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnatras)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camsecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpuKeyTyped
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = cpu.getText().length() - 1;
            String n = cpu.getText().substring(0, k);
            cpu.setText(n);
        }
        int numerocaracteres = 1;
        if (cpu.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 2 caracteres");

        }
        int rango;
        //rango=Integer.parseInt(cpu.getText());
        System.out.println(cpu.getText());
        // if(rango<0 || rango>12){
        //JOptionPane.showMessageDialog(rootPane, "Solo numeros entre 1 y 12");
        // }

    }//GEN-LAST:event_cpuKeyTyped

    private void cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuActionPerformed

    }//GEN-LAST:event_cpuActionPerformed

    private void pantallaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pantallaKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = pantalla.getText().length() - 1;
            String n = pantalla.getText().substring(0, k);
            pantalla.setText(n);
        }
        int numerocaracteres = 2;
        if (pantalla.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 3 caracteres");

        }
        double rango = 0;
        rango = Double.parseDouble(pantalla.getText());
        if (rango < 3.0 || rango > 6.7) {
            JOptionPane.showMessageDialog(null, "Solo numeros entre 3.0 y 6.7");
            pantalla.setText("");
        }
    }//GEN-LAST:event_pantallaKeyReleased

    private void ramKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramKeyTyped

    }//GEN-LAST:event_ramKeyTyped

    private void ramKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = ram.getText().length() - 1;
            String n = ram.getText().substring(0, k);
            ram.setText(n);
        }
        int numerocaracteres = 2;
        if (ram.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 3 caracteres");

        }
        int rango = 0;
        if (ram.getText().compareTo("") != 0) {
            rango = Integer.parseInt(ram.getText());
        }

        if (rango < 0.5 || rango > 6.0) {
            JOptionPane.showMessageDialog(null, "Solo numeros entre 0.5 y 6.0");
            ram.setText("");
        }


    }//GEN-LAST:event_ramKeyReleased

    private void garantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garantiaKeyTyped
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = garantia.getText().length() - 1;
            String n = garantia.getText().substring(0, k);
            garantia.setText(n);
        }
        int numerocaracteres = 1;
        if (garantia.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 2 caracteres");

        }

    }//GEN-LAST:event_garantiaKeyTyped

    private void precioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = precio.getText().length() - 1;
            String n = precio.getText().substring(0, k);
            precio.setText(n);
        }
        int numerocaracteres = 5;
        if (precio.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 6 caracteres");

        }
        double rango = 0;
        if (precio.getText().compareTo("") != 0) {
            rango = Double.parseDouble(precio.getText());
        }

        if (rango < 0.01 || rango > 999.99) {
            JOptionPane.showMessageDialog(null, "Solo numeros entre 0.01 y 999.99");
            precio.setText("");
        }
    }//GEN-LAST:event_precioKeyReleased

    private void cpuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpuKeyReleased
        int rango = 0;
        if (cpu.getText().compareTo("") != 0) {
            rango = Integer.parseInt(cpu.getText());
        }

        if (rango < 0 || rango > 12) {
            JOptionPane.showMessageDialog(null, "Solo numeros entre 1 y 12");
        }


    }//GEN-LAST:event_cpuKeyReleased

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if (jCheckBox1.isSelected()) {
            camprincipal.setEnabled(true);
        } else {
            camprincipal.setEnabled(false);
            camprincipal.setText("");
        }


    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        total.setPantalla(Integer.parseInt(pantalla.getText()));
        total.setBateria(Integer.parseInt(bateria.getText()));
        total.setPrecio(Double.parseDouble(precio.getText()));
        total.setCamprincipal(Integer.parseInt(camprincipal.getText()));
        total.setCamsecundaria(Integer.parseInt(camsecundaria.getText()));
        total.setMarca(jComboBox1.getSelectedItem().toString());
        total.setGarantia(Integer.parseInt(garantia.getText()));
        total.setCpu(Integer.parseInt(cpu.getText()));
        total.setRam(Integer.parseInt(ram.getText()));
        total.setFlash(jCheckBox3.isSelected());
        if (total.mostrar() <= 7) {
            jTextArea1.setText("El terminal no es buena inversion");
        } else if (total.mostrar() <= 14) {
            jTextArea1.setText("Es una inversion de riesgo");
        } else if (total.mostrar() <= 21) {
            jTextArea1.setText("La inversion es viable");
        } else {
            jTextArea1.setText("Es una buena inversion");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        if (jCheckBox2.isSelected()) {
            camsecundaria.setEnabled(true);
        }


    }//GEN-LAST:event_jCheckBox2StateChanged

    private void garantiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garantiaKeyReleased
        int rango = 0;
        if (garantia.getText().compareTo("") != 0) {
            rango = Integer.parseInt(garantia.getText());
        }

        if (rango < 1 || rango > 24) {
            JOptionPane.showMessageDialog(null, "Solo numeros entre 1 y 24");
            garantia.setText("");
        }


    }//GEN-LAST:event_garantiaKeyReleased

    private void camprincipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camprincipalKeyReleased
 String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = camprincipal.getText().length() - 1;
            String n = camprincipal.getText().substring(0, k);
            camprincipal.setText(n);
        }
        int numerocaracteres = 3;
        if (camprincipal.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 4 caracteres");    
        }
        
    }//GEN-LAST:event_camprincipalKeyReleased

    private void camsecundariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camsecundariaKeyReleased
 String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = camsecundaria.getText().length() - 1;
            String n = camsecundaria.getText().substring(0, k);
            camsecundaria.setText(n);
        }
        int numerocaracteres = 3;
        if (camsecundaria.getText().length() > numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 4 caracteres");
        }
    }//GEN-LAST:event_camsecundariaKeyReleased

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
            this.setVisible(false);
    FrmMenu objeto= new FrmMenu();
    objeto.setVisible(true);


    }//GEN-LAST:event_btnatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APP3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APP3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APP3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APP3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP3Y4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bateria;
    private javax.swing.JButton btnatras;
    private javax.swing.JTextField camprincipal;
    private javax.swing.JTextField camsecundaria;
    private javax.swing.JTextField cpu;
    private javax.swing.JTextField garantia;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pantalla;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField ram;
    // End of variables declaration//GEN-END:variables
}
